name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a sua branch principal se necessÃ¡rio

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Onde o Vite gera os arquivos estÃ¡ticos
          branch: gh-pages # Branch de destino para o deploy
